version: '3'
services:
  mysql:
    container_name: reach-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: contact_list
  php:
    container_name: reach-php
    build: ./docker/php
    entrypoint: ["sh", "/usr/local/bin/init.sh", "php-fpm","-F"]
    image: reach-php
    volumes:
      - .:/var/www/html
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE_DB: contact_list
    links:
      - mysql
    depends_on:
      - mysql
  nginx:
    container_name: reach-nginx
    build: ./docker/nginx
    image: reach-nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/servers/site.conf
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    links:
      - php
    depends_on:
      - php