/// dashboard
export const DASHBOARD_VISITED = 'DASHBOARD_VISITED';

/// auth
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOGIN_SCREEN_DISPLAYED = 'LOGIN_SCREEN_DISPLAYED';

/// contact list
export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const RECEIVED_ALL_CONTACTS = 'RECEIVED_ALL_CONTACTS';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const CONTACT_UPDATED = 'CONTACT_UPDATED';
export const RECEIVED_CONTACT_FOR_EDIT = 'RECEIVED_CONTACT_FOR_EDIT';
export const SAVE_CONTACT = 'SAVE_CONTACT';
export const CONTACT_SAVED = 'CONTACT_SAVED';
export const CREATE_CONTACT = 'CREATE_CONTACT';

/// user
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const RECEIVED_ALL_USERS = 'RECEIVED_ALL_USERS';
export const EDIT_USER = 'EDIT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_UPDATED = 'USER_UPDATED';
export const RECEIVED_USER_FOR_EDIT = 'RECEIVED_USER_FOR_EDIT';
export const SAVE_USER = 'SAVE_USER';
export const USER_SAVED = 'USER_SAVED';
export const CREATE_USER = 'CREATE_USER';